### ISSUE TITLE
Have the list clear when everything is deleted

### ISSUE THREAD

**Issue by philawsophizing** [FACN1/week4-hibas-angels#24]
When everything is deleted the search results from the last letter still show. I think we have the same problem. love the css lol.
![capture](https://cloud.githubusercontent.com/assets/22927754/23987174/ee878216-0a30-11e7-9b8d-69518860e1c7.PNG)

**Comment by MohamedOmarii** [comment]
#24

**Comment by MohamedOmarii** [comment]
@philawsophizing
